name: Build and Test (Flit)

on:
  push:
    branches: 
      - '**'  # This will trigger the workflow on push to any branch
  pull_request:
    branches: 
      - '**'  # This will trigger the workflow on pull requests to any branch

jobs:
  build-and-test-flit:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Check out repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you need

    # Step 3: Install Flit
    - name: Install Flit
      run: |
        pip install flit

    # Step 4: Install dependencies using Flit (with optional gdsfactory)
    - name: Install dependencies
      run: |
        export FLIT_ROOT_INSTALL=1  # Allow root installs
        flit install --deps=develop --extras=gdsfactory

    # Step 5: Run tests
    - name: Run tests
      run: |
        coverage run -m pytest
        coverage report

    # Step 6: Upload coverage reports to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Ensure you have set CODECOV_TOKEN as a secret in GitHub
